force-app/main/default/objects/Achievement__c/Achievement__c.object-meta.xml
<CustomObject>
    <description>Achievements are certifications and notable engagements a person would like to put on their Resume.</description>
    <label>Achievement</label>
    <nameField>
        <label>Acheivement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Achievements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Achievement__c/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <description>Order in which to display the Achievement</description>
    <label>Sort Order</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Achievement__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Achievement that Looks up to the User.</description>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Achievements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Experience__c/Experience__c.object-meta.xml
<CustomObject>
    <description>Track professional and educational experiences to display on a Resume.</description>
    <label>Experience</label>
    <nameField>
        <displayFormat>X-{0000}</displayFormat>
        <label>Experience Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Experiences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Experience__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to Accounts</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Experiences</relationshipLabel>
    <relationshipName>Experiences</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Experience__c/fields/Degree_Earned__c.field-meta.xml
<CustomField>
    <fullName>Degree_Earned__c</fullName>
    <description>Degree earned</description>
    <label>Degree Earned</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Experience__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Date Experience Ended</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Experience__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>Date experience started</description>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Experience__c/fields/Summary__c.field-meta.xml
<CustomField>
    <fullName>Summary__c</fullName>
    <description>Summary of the Experience</description>
    <label>Summary</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Experience__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>Title of the Experience</description>
    <inlineHelpText>Enter in your Job Title</inlineHelpText>
    <label>Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Experience__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>User the experience is associated with.</description>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Experiences</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Experience__c/recordTypes/Educational.recordType-meta.xml
<RecordType>
    <fullName>Educational</fullName>
    <active>true</active>
    <description>Educational Work Experience</description>
    <label>Educational</label>
</RecordType>

force-app/main/default/objects/Experience__c/recordTypes/Professional.recordType-meta.xml
<RecordType>
    <fullName>Professional</fullName>
    <active>true</active>
    <description>Professional Work Experience</description>
    <label>Professional</label>
</RecordType>

force-app/main/default/objects/Skillset__c/Skillset__c.object-meta.xml
<CustomObject>
    <description>Skills to be listed on a Resume</description>
    <label>Skillset</label>
    <nameField>
        <displayFormat>SK-{0000}</displayFormat>
        <label>Skillset Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Skillsets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Skillset__c/fields/Skills__c.field-meta.xml
<CustomField>
    <fullName>Skills__c</fullName>
    <description>List of Skills</description>
    <inlineHelpText>Enter in the skills for this type</inlineHelpText>
    <label>Skills</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Skillset__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of skillset</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Soft</fullName>
            </value>
            <value>
                <fullName>Technical</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Skillset__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to user for skill</description>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Skillsets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ResumePreviewControllerExtension.cls
/********************************************************************************************
 * ResumePreviewControllerExtension allows for custom lists for the ResumePreview VF Page	*
 * Authored by Jacques Grillot for the sfResume App											*
 * *****************************************************************************************/	
public with sharing class ResumePreviewControllerExtension {
	private final User me;
    
    // Extend the User object controller and get the Record
    public ResumePreviewControllerExtension(ApexPages.StandardController stdController){
        this.me = (User)stdController.getRecord();
    }
    
    // Declare the list for Certifications
    public List<Achievement__c> certifications;
    // Build a list of Achievements
    public List<Achievement__c> getCertifications(){
        if(certifications == null){
            certifications = [SELECT Id, Name, Sort_Order__c 
                                                    FROM Achievement__c
                                                    WHERE User__r.Id = :me.Id WITH SECURITY_ENFORCED
                                                    ORDER BY Sort_Order__c];
        }
        // Return the certification records for rendering
        return certifications;
    }
    
    // Declare the list for Skills
    public List<Skillset__c> skills;
    // Build a list of Skills
    public List<Skillset__c> getSkills(){
        if(skills == null){
            skills = [SELECT Id, Name, Type__c, Skills__c
                                    FROM Skillset__c
                                    WHERE User__r.Id = :me.Id WITH SECURITY_ENFORCED
                                    ORDER BY Type__c];
        }
        // Return the skill records for rendering
        return skills;

    }
    
    // Declare a list for Jobs
    public List<Experience__c> jobs;
    // Build a list of Experiences filtering for Professional experiences
    public List<Experience__c> getJobs(){
        if(jobs == null){
            jobs = [SELECT Id, Name, Title__c, Account__r.Name, Summary__c, Start_Date__c, End_Date__c
                                FROM Experience__c
                                WHERE User__r.Id = :me.Id
                                AND RecordType.Name='Professional' WITH SECURITY_ENFORCED
                                ORDER BY Start_Date__c DESC];
        }
        return jobs;
    }
    
    // Declare a list for Educational accomplishments
    public List<Experience__c> edus;
    // Build a list of Experiences filtering for Educational experiences
    public List<Experience__c> getEdus(){
        if(edus == null){
            edus = [SELECT Id, Name, Degree_Earned__c, Account__r.Name, Summary__c, End_Date__c
                                FROM Experience__c
                                WHERE User__r.Id = :me.Id
                                AND RecordType.Name='Educational' WITH SECURITY_ENFORCED
                                ORDER BY End_Date__c DESC];
        }
        return edus;
    }
}